version: '3.5'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  worker:
    image: celery-test-worker:latest
    container_name: celery-test-worker
    build:
      context: celery-worker
      dockerfile: Dockerfile
    depends_on:
      - redis

  app:
    image: celery-test-app:latest
    container_name: celery-test-app
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - redis
      - worker
    ports:
    - 8080:8080
